// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as ValidationUtils from "./ValidationUtils/ValidationUtils.res.js";

function map(fn, validation) {
  if (validation.TAG === "Valid") {
    return {
            TAG: "Valid",
            _0: fn(validation._0)
          };
  } else {
    return {
            TAG: "Invalid",
            _0: validation._0
          };
  }
}

function bind(validation, fn) {
  if (validation.TAG === "Valid") {
    return fn(validation._0);
  } else {
    return {
            TAG: "Invalid",
            _0: validation._0
          };
  }
}

var Validation = {
  map: map,
  bind: bind
};

function create(value) {
  var uuidRegex = new RegExp("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$");
  if (uuidRegex.test(value.toLowerCase())) {
    return {
            TAG: "Valid",
            _0: value
          };
  } else {
    return {
            TAG: "Invalid",
            _0: ["Invalid UUID format"]
          };
  }
}

var Uuid = {
  create: create
};

function create$1(date) {
  var now = Date.now();
  var inputTime = date.getTime();
  if (inputTime > now) {
    return {
            TAG: "Invalid",
            _0: ["Timestamp cannot be in the future"]
          };
  } else if (inputTime < now - 365.0 * 24.0 * 60.0 * 60.0 * 1000.0) {
    return {
            TAG: "Invalid",
            _0: ["Timestamp is too far in the past"]
          };
  } else {
    return {
            TAG: "Valid",
            _0: date
          };
  }
}

var Timestamp = {
  create: create$1
};

function create$2(latitude, longitude) {
  var coords = {
    latitude: latitude,
    longitude: longitude
  };
  if (latitude >= -90.0 && latitude <= 90.0 && longitude >= -180.0 && longitude <= 180.0) {
    return {
            TAG: "Valid",
            _0: coords
          };
  } else {
    return {
            TAG: "Invalid",
            _0: ["Invalid coordinates: latitude must be between -90 and 90, longitude between -180 and 180"]
          };
  }
}

function isValid(coords) {
  var match = create$2(coords.latitude, coords.longitude);
  if (match.TAG === "Valid") {
    return true;
  } else {
    return false;
  }
}

function fromRecord(record) {
  return create$2(record.latitude, record.longitude);
}

var Coordinates = {
  create: create$2,
  isValid: isValid,
  fromRecord: fromRecord
};

function create$3(coordinates, address, barangay, city, province) {
  var errors = fromRecord(coordinates);
  if (errors.TAG !== "Valid") {
    return {
            TAG: "Invalid",
            _0: errors._0
          };
  }
  var validations = [
    ValidationUtils.isNotEmpty(barangay, "Barangay"),
    ValidationUtils.isNotEmpty(city, "City"),
    ValidationUtils.isNotEmpty(province, "Province"),
    ValidationUtils.hasMinLength(barangay, 2, "Barangay"),
    ValidationUtils.hasMinLength(city, 2, "City"),
    ValidationUtils.hasMinLength(province, 2, "Province")
  ];
  var errors$1 = ValidationUtils.validateAll(validations);
  if (errors$1.length > 0) {
    return {
            TAG: "Invalid",
            _0: errors$1
          };
  } else {
    return {
            TAG: "Valid",
            _0: {
              coordinates: errors._0,
              address: address,
              barangay: barangay,
              city: city,
              province: province
            }
          };
  }
}

function fromRecord$1(record) {
  return create$3(record.coordinates, Core__Option.getOr(record.address, ""), record.barangay, record.city, record.province);
}

var $$Location = {
  create: create$3,
  fromRecord: fromRecord$1
};

function create$4(value) {
  if (value >= 0.0 && value <= 100.0) {
    return {
            TAG: "Valid",
            _0: value
          };
  } else {
    return {
            TAG: "Invalid",
            _0: ["Percentage must be between 0 and 100"]
          };
  }
}

function toDecimal(percentage) {
  return percentage / 100.0;
}

function fromDecimal(decimal) {
  return create$4(decimal * 100.0);
}

function clamp(value) {
  return Math.min(Math.max(value, 0.0), 100.0);
}

var Percentage = {
  create: create$4,
  toDecimal: toDecimal,
  fromDecimal: fromDecimal,
  clamp: clamp
};

export {
  Validation ,
  Uuid ,
  Timestamp ,
  Coordinates ,
  $$Location ,
  Percentage ,
}
/* ValidationUtils Not a pure module */
