// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_array from "rescript/lib/es6/js_array.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.js";

function isNotEmpty(value, fieldName) {
  if (value === "") {
    return fieldName + " cannot be empty";
  }
  
}

function hasMinLength(value, minLength, fieldName) {
  if (value.length < minLength) {
    return fieldName + " must be at least " + minLength.toString() + " characters";
  }
  
}

function hasMaxLength(value, maxLength, fieldName) {
  if (value.length > maxLength) {
    return fieldName + " must be at most " + maxLength.toString() + " characters";
  }
  
}

function matchesPattern(value, pattern, fieldName, errorMsg) {
  if (!pattern.test(value)) {
    return fieldName + " " + errorMsg;
  }
  
}

function isInRange(value, min, max, fieldName) {
  if (value < min || value > max) {
    return fieldName + " must be between " + min.toString() + " and " + max.toString();
  }
  
}

function isPositive(value, fieldName) {
  if (value < 0) {
    return fieldName + " must be positive";
  }
  
}

var emailRegex = new RegExp("^[^@]+@[^@]+\\.[^@]+$");

function isValidEmail(email) {
  if (email === "") {
    return "Email cannot be empty";
  }
  if (email.length > 254) {
    return "Email address too long";
  }
  if ("..".includes(email)) {
    return "Invalid email format: consecutive dots";
  }
  if (".".startsWith(email) || ".".endsWith(email)) {
    return "Invalid email format: cannot start or end with dot";
  }
  if (!emailRegex.test(email)) {
    return "Invalid email format";
  }
  var suspiciousPatterns = [
    "<script",
    "javascript:",
    "data:",
    "vbscript:",
    "onload=",
    "onerror=",
    "../",
    "\\",
    "|",
    "`",
    "$",
    "!",
    "'",
    "\"",
    "(",
    ")",
    "{",
    "}",
    "[",
    "]"
  ];
  var hasSuspiciousPattern = Js_array.some((function (pattern) {
          return pattern.includes(email);
        }), suspiciousPatterns);
  if (hasSuspiciousPattern) {
    return "Email contains potentially unsafe characters";
  }
  
}

function escapeHtml(unsafe) {
  return unsafe.replace(new RegExp("&"), "&").replace(new RegExp("<"), "<").replace(new RegExp(">"), ">").replace(new RegExp("\""), "&quot").replace(new RegExp("'"), "&#x27;").replace(new RegExp("/"), "&#x2F;");
}

var secureUrlRegex = new RegExp("https://.+");

var devUrlRegex = new RegExp("^https?://.+");

function isValidUrl(url, isProductionOpt) {
  var isProduction = isProductionOpt !== undefined ? isProductionOpt : true;
  var urlRegex = isProduction ? secureUrlRegex : devUrlRegex;
  if (url === "") {
    return "URL cannot be empty";
  }
  if (url.length > 2048) {
    return "URL too long";
  }
  if (!urlRegex.test(url)) {
    if (isProduction) {
      return "Invalid URL format. Only HTTPS URLs are allowed in production.";
    } else {
      return "Invalid URL format";
    }
  }
  var dangerousPatterns = [
    "javascript:",
    "data:",
    "vbscript:",
    "file:",
    "ftp:",
    "../",
    "..\\",
    "%2e%2e",
    "\\x2e\\x2e",
    "<!--",
    "-->",
    "<script",
    "onload=",
    "onerror=",
    "onclick="
  ];
  var hasDangerousPattern = Js_array.some((function (pattern) {
          return pattern.includes(url);
        }), dangerousPatterns);
  if (hasDangerousPattern) {
    return "URL contains potentially unsafe content";
  }
  
}

var phoneRegex = new RegExp("^[0-9+\\-\\s()]+$");

function isValidPhone(phone) {
  if (!phoneRegex.test(phone)) {
    return "Invalid phone number format";
  }
  
}

function validateAll(validations) {
  return Core__Array.filterMap(validations, (function (x) {
                return x;
              }));
}

export {
  isNotEmpty ,
  hasMinLength ,
  hasMaxLength ,
  matchesPattern ,
  isInRange ,
  isPositive ,
  emailRegex ,
  isValidEmail ,
  escapeHtml ,
  secureUrlRegex ,
  devUrlRegex ,
  isValidUrl ,
  phoneRegex ,
  isValidPhone ,
  validateAll ,
}
/* emailRegex Not a pure module */
