// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Crypto from "crypto";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as ValidationUtils from "../ValidationUtils/ValidationUtils.res.js";

function toString(role) {
  if (role === "User") {
    return "user";
  } else {
    return "admin";
  }
}

function fromString(str) {
  switch (str) {
    case "admin" :
        return "Admin";
    case "user" :
        return "User";
    default:
      return ;
  }
}

function canManageOutages(role) {
  if (role === "User") {
    return false;
  } else {
    return true;
  }
}

function canManageUsers(role) {
  if (role === "User") {
    return false;
  } else {
    return true;
  }
}

var Role = {
  toString: toString,
  fromString: fromString,
  canManageOutages: canManageOutages,
  canManageUsers: canManageUsers
};

var $$Buffer = {};

function create(id, email, firstName, lastName, role, isActiveOpt, createdAt, updatedAt, lastLoginAt) {
  var isActive = isActiveOpt !== undefined ? isActiveOpt : true;
  var user = {
    id: id,
    email: email,
    firstName: firstName,
    lastName: lastName,
    role: role,
    isActive: isActive,
    createdAt: createdAt,
    updatedAt: updatedAt,
    lastLoginAt: lastLoginAt
  };
  var validations = [
    ValidationUtils.isNotEmpty(email, "Email"),
    ValidationUtils.isValidEmail(email),
    ValidationUtils.hasMinLength(email, 5, "Email"),
    ValidationUtils.hasMaxLength(email, 255, "Email"),
    ValidationUtils.isNotEmpty(firstName, "First name"),
    ValidationUtils.hasMinLength(firstName, 1, "First name"),
    ValidationUtils.hasMaxLength(firstName, 100, "First name"),
    ValidationUtils.isNotEmpty(lastName, "Last name"),
    ValidationUtils.hasMinLength(lastName, 1, "Last name"),
    ValidationUtils.hasMaxLength(lastName, 100, "Last name")
  ];
  var errors = ValidationUtils.validateAll(validations);
  if (errors.length > 0) {
    return {
            TAG: "Invalid",
            _0: errors
          };
  } else {
    return {
            TAG: "Valid",
            _0: user
          };
  }
}

function updateLastLogin(user) {
  return {
          id: user.id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: user.role,
          isActive: user.isActive,
          createdAt: user.createdAt,
          updatedAt: new Date(),
          lastLoginAt: Caml_option.some(new Date())
        };
}

function deactivate(user) {
  return {
          id: user.id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: user.role,
          isActive: false,
          createdAt: user.createdAt,
          updatedAt: new Date(),
          lastLoginAt: user.lastLoginAt
        };
}

function activate(user) {
  return {
          id: user.id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: user.role,
          isActive: true,
          createdAt: user.createdAt,
          updatedAt: new Date(),
          lastLoginAt: user.lastLoginAt
        };
}

function changeRole(user, newRole) {
  return {
          id: user.id,
          email: user.email,
          firstName: user.firstName,
          lastName: user.lastName,
          role: newRole,
          isActive: user.isActive,
          createdAt: user.createdAt,
          updatedAt: new Date(),
          lastLoginAt: user.lastLoginAt
        };
}

function fullName(user) {
  return user.firstName + " " + user.lastName;
}

function canPerformAction(user, action) {
  switch (action) {
    case "manage_outages" :
        return canManageOutages(user.role);
    case "manage_users" :
        return canManageUsers(user.role);
    case "view_dashboard" :
        return user.isActive;
    default:
      return false;
  }
}

function isEligibleForNotifications(user) {
  return user.isActive;
}

function create$1(userId, token, expiresAt, createdAt, ipAddress, userAgent) {
  var session = {
    userId: userId,
    token: token,
    expiresAt: expiresAt,
    createdAt: createdAt,
    ipAddress: ipAddress,
    userAgent: userAgent
  };
  var mut_errors = [];
  if (token === "") {
    mut_errors.push("Token cannot be empty");
  }
  if (token.length < 32) {
    mut_errors.push("Token must be at least 32 characters");
  }
  if (expiresAt.getTime() <= createdAt.getTime()) {
    mut_errors.push("Session expiration must be after creation");
  }
  var maxSessionMs = 24.0 * 60.0 * 60.0 * 1000.0;
  if (expiresAt.getTime() - createdAt.getTime() > maxSessionMs) {
    mut_errors.push("Session duration exceeds maximum allowed time");
  }
  if (mut_errors.length !== 0) {
    return {
            TAG: "Invalid",
            _0: mut_errors
          };
  } else {
    return {
            TAG: "Valid",
            _0: session
          };
  }
}

function isExpired(session) {
  return session.expiresAt.getTime() <= new Date().getTime();
}

function timeUntilExpiry(session) {
  return session.expiresAt.getTime() - new Date().getTime();
}

function isValidForIp(session, ipAddress) {
  var sessionIp = session.ipAddress;
  if (sessionIp !== undefined) {
    return sessionIp === ipAddress;
  } else {
    return true;
  }
}

function isValidForUserAgent(session, userAgent) {
  var sessionUserAgent = session.userAgent;
  if (sessionUserAgent !== undefined) {
    return sessionUserAgent === userAgent;
  } else {
    return true;
  }
}

function shouldRotate(session) {
  return timeUntilExpiry(session) < 60.0 * 60.0 * 1000.0;
}

function generateSecureToken() {
  return $$Crypto.randomBytes(32).toString("hex");
}

function refresh(session, newExpiresAt) {
  var newToken = $$Crypto.randomBytes(32).toString("hex");
  return create$1(session.userId, newToken, newExpiresAt, new Date(), Core__Option.getOr(session.ipAddress, ""), Core__Option.getOr(session.userAgent, ""));
}

var Session = {
  create: create$1,
  isExpired: isExpired,
  timeUntilExpiry: timeUntilExpiry,
  isValidForIp: isValidForIp,
  isValidForUserAgent: isValidForUserAgent,
  shouldRotate: shouldRotate,
  generateSecureToken: generateSecureToken,
  refresh: refresh
};

export {
  Role ,
  $$Buffer ,
  create ,
  updateLastLogin ,
  deactivate ,
  activate ,
  changeRole ,
  fullName ,
  canPerformAction ,
  isEligibleForNotifications ,
  Session ,
}
/* crypto Not a pure module */
