// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "../Core.res.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ValidationUtils from "../ValidationUtils/ValidationUtils.res.js";

function toString(status) {
  switch (status) {
    case "Unverified" :
        return "unverified";
    case "Verified" :
        return "verified";
    case "InProgress" :
        return "in_progress";
    case "Resolved" :
        return "resolved";
    
  }
}

function fromString(str) {
  switch (str) {
    case "in_progress" :
        return "InProgress";
    case "resolved" :
        return "Resolved";
    case "unverified" :
        return "Unverified";
    case "verified" :
        return "Verified";
    default:
      return ;
  }
}

function canTransition(from, to_) {
  switch (from) {
    case "Unverified" :
        switch (to_) {
          case "Unverified" :
          case "InProgress" :
              return false;
          case "Verified" :
          case "Resolved" :
              return true;
          
        }
    case "Verified" :
        switch (to_) {
          case "Unverified" :
          case "Verified" :
              return false;
          case "InProgress" :
          case "Resolved" :
              return true;
          
        }
    case "InProgress" :
        if (to_ === "Resolved") {
          return true;
        } else {
          return false;
        }
    case "Resolved" :
        if (to_ === "InProgress") {
          return true;
        } else {
          return false;
        }
    
  }
}

var Status = {
  toString: toString,
  fromString: fromString,
  canTransition: canTransition
};

function create(id, status, confidencePercentage, title, description, $$location, affectedCustomersOpt, estimatedRestoration, actualRestoration, reportedAt, createdAt, updatedAt) {
  var affectedCustomers = affectedCustomersOpt !== undefined ? affectedCustomersOpt : 0;
  var confidenceValidation = Core.Percentage.create(confidencePercentage);
  return Core.Validation.bind(confidenceValidation, (function (confidence) {
                var safeTitle = ValidationUtils.escapeHtml(title);
                var safeDescription = description !== undefined ? ValidationUtils.escapeHtml(description) : undefined;
                var outage = {
                  id: id,
                  status: status,
                  confidencePercentage: confidence,
                  title: safeTitle,
                  description: safeDescription,
                  location: $$location,
                  affectedCustomers: affectedCustomers,
                  estimatedRestoration: estimatedRestoration,
                  actualRestoration: actualRestoration,
                  reportedAt: reportedAt,
                  createdAt: createdAt,
                  updatedAt: updatedAt
                };
                var mut_errors = [];
                if (title === "") {
                  mut_errors.push("Title cannot be empty");
                }
                if (affectedCustomers < 0) {
                  mut_errors.push("Affected customers cannot be negative");
                }
                if (!Core.Coordinates.isValid($$location.coordinates)) {
                  mut_errors.push("Invalid location coordinates");
                }
                var suspiciousPatterns = [
                  "<script",
                  "javascript:",
                  "onload=",
                  "onerror="
                ];
                var hasSuspiciousPattern = Belt_Array.some(suspiciousPatterns, (function (pattern) {
                        return pattern.includes(title);
                      }));
                if (hasSuspiciousPattern) {
                  mut_errors.push("Title contains potentially unsafe content");
                }
                if (mut_errors.length > 0) {
                  return {
                          TAG: "Invalid",
                          _0: mut_errors
                        };
                } else {
                  return {
                          TAG: "Valid",
                          _0: outage
                        };
                }
              }));
}

function isActive(outage) {
  var match = outage.status;
  if (match === "Resolved") {
    return false;
  } else {
    return true;
  }
}

function updateStatus(outage, newStatus) {
  if (canTransition(outage.status, newStatus)) {
    return {
            TAG: "Valid",
            _0: {
              id: outage.id,
              status: newStatus,
              confidencePercentage: outage.confidencePercentage,
              title: outage.title,
              description: outage.description,
              location: outage.location,
              affectedCustomers: outage.affectedCustomers,
              estimatedRestoration: outage.estimatedRestoration,
              actualRestoration: outage.actualRestoration,
              reportedAt: outage.reportedAt,
              createdAt: outage.createdAt,
              updatedAt: new Date()
            }
          };
  } else {
    return {
            TAG: "Invalid",
            _0: ["Invalid status transition"]
          };
  }
}

function markAsResolved(outage) {
  return Core.Validation.map((function (updatedOutage) {
                return {
                        id: updatedOutage.id,
                        status: updatedOutage.status,
                        confidencePercentage: updatedOutage.confidencePercentage,
                        title: updatedOutage.title,
                        description: updatedOutage.description,
                        location: updatedOutage.location,
                        affectedCustomers: updatedOutage.affectedCustomers,
                        estimatedRestoration: updatedOutage.estimatedRestoration,
                        actualRestoration: Caml_option.some(new Date()),
                        reportedAt: updatedOutage.reportedAt,
                        createdAt: updatedOutage.createdAt,
                        updatedAt: updatedOutage.updatedAt
                      };
              }), updateStatus(outage, "Resolved"));
}

function calculateEstimatedRestoration(outage) {
  var match = outage.status;
  switch (match) {
    case "Unverified" :
        return ;
    case "Verified" :
        var baseTime = new Date();
        return Caml_option.some(new Date(baseTime.getTime() + 6.0 * 60.0 * 60.0 * 1000.0));
    case "InProgress" :
        var baseTime$1 = new Date();
        return Caml_option.some(new Date(baseTime$1.getTime() + 2.0 * 60.0 * 60.0 * 1000.0));
    case "Resolved" :
        return outage.actualRestoration;
    
  }
}

function isHighConfidence(outage) {
  return outage.confidencePercentage >= 80.0;
}

function isCritical(outage) {
  if (outage.affectedCustomers > 100) {
    return outage.confidencePercentage >= 80.0;
  } else {
    return false;
  }
}

export {
  Status ,
  create ,
  isActive ,
  updateStatus ,
  markAsResolved ,
  calculateEstimatedRestoration ,
  isHighConfidence ,
  isCritical ,
}
/* Core Not a pure module */
